Changed arguments format to match stellar

diff --git a/solang-stellar b/solang-stellar
--- a/solang-stellar
+++ b/solang-stellar
@@ -165,6 +165,15 @@ while [[ $# -gt 0 ]]; do
       usage
       exit 0
       ;;
+    -[a-zA-Z])
+      if [[ $# -lt 2 ]]; then
+        err "Missing value for $1"
+        exit 2
+      fi
+      short_name="${1#-}"
+      invoke_args+=("--$short_name" "$2")
+      shift 2
+      ;;
     --)
       shift
       break
